FROM node:22-alpine AS base

WORKDIR /app

COPY package*.json ./
COPY prisma.config.ts tsconfig.json ./
COPY src/lib/prisma ./src/lib/prisma

RUN npm ci

COPY . .

RUN npm run worker:build

ENV NODE_ENV=production

CMD ["npm", "run", "worker:start"]