// =============================================================================
// src/repositories/verification-token.repository.ts
// =============================================================================
//
// This repository handles all database operations for VerificationToken.
// Used by two distinct flows:
//   1. EMAIL VERIFICATION: After registration, user clicks link in email
//   2. PASSWORD RESET: User forgot password, clicks link in email
//
// SECURITY DESIGN PRINCIPLE — "Use Once, Delete Immediately":
// Every token must be deleted after it's consumed (used).
// Leaving valid tokens in the database is a security vulnerability.
// If the database were compromised, attackers could use old tokens.
//
// TOKEN LIFECYCLE:
//   CREATE → email sent → user clicks → FIND → verify expiry → DELETE
//   If user doesn't click → token expires → we clean up on next request

import { prisma } from "../lib/prisma/prisma";
import { TokenType } from "@/generated/prisma/client";

// Re-export TokenType so callers don't need to import from generated
export { TokenType };

export const verificationTokenRepository = {
  // ============================================================================
  // CREATE: Store a new verification token
  // ============================================================================

  /**
   * Save a new token to the database.
   *
   * The token string itself is generated by the calling service using:
   *   import crypto from 'crypto'
   *   const token = crypto.randomBytes(32).toString('hex')
   *   // → "a3f5b9..." (64 hex chars = 256 bits of randomness)
   *
   * WHY NOT GENERATE THE TOKEN HERE?
   * The repository's job is database I/O, not business logic.
   * Token generation is business logic → belongs in the auth service.
   * This is "Single Responsibility Principle" in practice.
   *
   * @param userId - The user this token belongs to
   * @param token - The pre-generated random token string
   * @param type - What this token is for (EMAIL_VERIFICATION or PASSWORD_RESET)
   * @param expiresAt - When this token expires
   */
  async create(
    userId: string,
    token: string,
    type: TokenType,
    expiresAt: Date
  ) {
    return prisma.verificationToken.create({
      data: {
        userId,
        token,
        type,
        expiresAt,
      },
    });
  },

  // ============================================================================
  // FIND: Look up a token
  // ============================================================================

  /**
   * Find a token by its string value.
   *
   * WHY find by `token` and not by `id`?
   * The user arrives with the token string from their email link.
   * They don't have the database ID — they have the token value.
   * Since token has @unique, findUnique works perfectly here.
   *
   * We also fetch the user relation to avoid a second DB query.
   * This is called "eager loading" in ORM terminology.
   * Without it:
   *   1. findByToken() → get userId
   *   2. userRepository.findById(userId) → get user
   *   That's 2 round trips to the DB.
   * With `include: { user: true }`:
   *   1. findByToken() → get token AND user in one SQL JOIN
   *   That's 1 round trip. Always more efficient.
   */
  async findByToken(token: string) {
    return prisma.verificationToken.findUnique({
      where: { token },
      include: {
        // Fetch the related User in the same query
        user: {
          select: {
            id: true,
            email: true,
            username: true,
            isVerified: true,
          },
        },
      },
    });
  },

  /**
   * Find the most recent token of a specific type for a user.
   * Used to check "does this user already have a pending token?"
   * before deciding whether to create a new one or reuse.
   */
  async findLatestByUserAndType(userId: string, type: TokenType) {
    return prisma.verificationToken.findFirst({
      where: { userId, type },
      orderBy: { createdAt: "desc" }, // most recent first
    });
  },

  // ============================================================================
  // DELETE: Consume a token after use
  // ============================================================================

  /**
   * Delete a token by its string value.
   * Called immediately after successful verification.
   *
   * IMPORTANT: This MUST be called after every successful token use.
   * Never leave a valid, consumed token in the database.
   */
  async deleteByToken(token: string) {
    return prisma.verificationToken.delete({
      where: { token },
    });
  },

  /**
   * Delete all tokens of a specific type for a user.
   * Used when:
   * - User requests a new verification email → invalidate old one
   * - User successfully resets password → delete all password reset tokens
   *
   * deleteMany() doesn't fail if no records match (unlike delete()).
   * This is safe to call even if no tokens exist.
   */
  async deleteByUserAndType(userId: string, type: TokenType) {
    return prisma.verificationToken.deleteMany({
      where: { userId, type },
    });
  },

  // ============================================================================
  // VALIDATION HELPER: Is this token still valid?
  // ============================================================================

  /**
   * Check if a token record has expired.
   * Pure utility — no database query.
   *
   * WHY NOT check this in the route handler?
   * We keep all token-related logic in this repository/service boundary.
   * The route handler just calls this helper — it doesn't know how
   * expiry is determined. Separation of concerns.
   */
  isExpired(token: { expiresAt: Date }): boolean {
    return token.expiresAt < new Date();
  },
};

// =============================================================================
// COMPLETE VERIFICATION FLOW EXAMPLE:
//
// // In your email verification API handler:
// const record = await verificationTokenRepository.findByToken(token)
//
// if (!record) {
//   return Response.json({ error: 'Invalid token' }, { status: 400 })
// }
//
// if (verificationTokenRepository.isExpired(record)) {
//   await verificationTokenRepository.deleteByToken(token) // clean up expired
//   return Response.json({ error: 'Token expired' }, { status: 400 })
// }
//
// // Token is valid — mark user verified and clean up token atomically
// await Promise.all([
//   userRepository.markVerified(record.userId),
//   verificationTokenRepository.deleteByToken(token), // consume immediately
// ])
//
// return Response.json({ success: true })
// =============================================================================
